spring.application.name=bys_api

# ======== DATABASE ========
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/api/v1

# ======== JWT ========
jwt.secret.key=${JWT_KEY}

# ======== EMAIL (OTP) ========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_EMAIL}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust= smtp.gmail.com

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate=INFO
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.beans=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.oauth2=TRACE

# ======== OAUTH2 - FINAL USER ========
spring.security.oauth2.client.registration.google-user.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google-user.client-secret=${SECRET_CLIENT}
spring.security.oauth2.client.registration.google-user.scope=openid,profile,email
spring.security.oauth2.client.registration.google-user.redirect-uri=http://localhost:8080/api/login/oauth2/code/google-user
spring.security.oauth2.client.registration.google-user.provider=google

## ======== OAUTH2 - SERVICE PROVIDER ========
#spring.security.oauth2.client.registration.google-provider.client-id=${CLIENT_ID}
#spring.security.oauth2.client.registration.google-provider.client-secret=${CLIENT_SECRET}
#spring.security.oauth2.client.registration.google-provider.scope=openid,profile,email
#spring.security.oauth2.client.registration.google-provider.redirect-uri={baseUrl}/login/oauth2/code/google-provider
#spring.security.oauth2.client.registration.google-provider.provider=google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

spring.security.oauth2.client.registration.google.client-id=${AUD_CLIENT_ID}
spring.security.oauth2.client.registration.google.scope=openid, profile, email

config.aws.access_key=${AWS_ACCESS_KEY}
config.aws.secret_access_key=${AWS_SECRET_ACCESS_KEY}

media.url=https://media-dev.adondevamos.app/
media.bucket=adv-dev-images

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB