spring.application.name=bys_api

spring.datasource.url=jdbc:postgresql://localhost:5432/bys_db
spring.datasource.username=admin
spring.datasource.password=ZM0MdIPLztVkjI7ERRs7
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/api